opencti:
  url: 'http://opencti:8080'
  token: '4b55edea-67e5-4dd0-8e12-ccfe0a843e5b'

connector:
  id: 'aed15720-9336-4ff8-907f-ac900aefca29'
  type: 'EXTERNAL_IMPORT'
  name: 'AlienVaultDEV'
  scope: 'alienvault'
  confidence_level: 15 # From 0 (Unknown) to 100 (Fully trusted)
  update_existing_data: false
  log_level: 'info'

alienvault:
  base_url: 'https://otx.alienvault.com'
  api_key: 'bfd468ab998aa284204742a09920e611ce9c9042c42db83a3b46cc81048558fe'
  tlp: 'White'
  create_observables: true
  create_indicators: true
  pulse_start_timestamp: '2020-05-01T00:00:00'  # ISO 8601
  report_type: 'threat-report'
  report_status: 'New'                                          # New, In progress, Analyzed and Closed
  guess_malware: false                                          # Use tags to guess malware
  guess_cve: false                                              # Use tags to guess CVE
  excluded_pulse_indicator_types: 'FileHash-MD5,FileHash-SHA1'  # Excluded Pulse indicator types
  enable_relationships: true                                    # Enable/Disable relationship creation between SDOs
  enable_attack_patterns_indicates: true                        # Enable/Disable "indicates" relationships between indicators and attack patterns
  filter_indicators: true                                       # Filter indicators by their created datetime
  interval_sec: 1800                                            # Seconds
